#!/usr/bin/env python3
"""Run reproducible multi-seed validation and enforce both identity safety gates."""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
import time
import unittest
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Callable

from _local.attest import bound_sentence, clopper_pearson_upper, runtime_provenance, sha256_file, utc_now
from _local.identity import ResolutionConfig, resolve_pair
from _local.metrics import summarize
import os as _os
import sys as _sys
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
from _lib.seeding import trial_seeds
from generate_synthetic_data import generate_pairs, write_sample_pack

ROOT = Path(__file__).resolve().parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--same", type=int, default=160)
    parser.add_argument("--different", type=int, default=240)
    parser.add_argument("--name-only", type=int, default=80)
    parser.add_argument("--trials", type=int, default=1)
    parser.add_argument("--engine", choices=("production", "negative-control"), default="production")
    parser.add_argument("--write-evidence", action=argparse.BooleanOptionalAction, default=None)
    parser.add_argument("--out", "--evidence-dir", dest="evidence_dir", type=Path, default=ROOT / "evidence")
    return parser.parse_args()


def run_unit_tests() -> tuple[bool, int]:
    suite = unittest.defaultTestLoader.discover(str(ROOT), pattern="test_identity.py")
    stream = io.StringIO()
    result = unittest.TextTestRunner(stream=stream, verbosity=0).run(suite)
    if not result.wasSuccessful():
        print(stream.getvalue(), file=sys.stderr)
    return result.wasSuccessful(), result.testsRun


def select_scorer(engine: str) -> Callable[[dict[str, Any], dict[str, Any]], dict[str, Any]]:
    if engine == "negative-control":
        from negative_control_scorer import score_pair
        return score_pair
    return resolve_pair


def score_rows(rows: list[dict[str, Any]], scorer: Callable, config: ResolutionConfig | None = None) -> list[dict[str, Any]]:
    scored = []
    for row in rows:
        if scorer is resolve_pair:
            decision = scorer(row["query"], row["candidate"], config)
        else:
            decision = scorer(row["query"], row["candidate"])
        scored.append({
            "pair_id": row["pair_id"], "label": row["label"], "category": row["category"],
            "disposition": decision["disposition"], "reason": decision["reason"],
            "shared_strong_identifier": decision.get("shared_strong_identifier", False),
        })
    return scored


def category_summary(rows: list[dict[str, Any]]) -> dict[str, dict[str, int]]:
    output: dict[str, Counter] = defaultdict(Counter)
    for row in rows:
        output[row["category"]][row["disposition"]] += 1
    return {category: dict(sorted(counts.items())) for category, counts in sorted(output.items())}


def gates(metrics: dict[str, Any]) -> dict[str, dict[str, Any]]:
    fn_pass = metrics["clear_false_negatives"] == 0
    merge_pass = (metrics["name_only_false_merges"] == 0
                  and metrics["structural_same_without_strong_id"] == 0
                  and metrics["auto_same_false_merges"] == 0)
    return {
        "false_negative": {
            "pass": fn_pass,
            "observed": metrics["clear_false_negatives"],
            "criterion": "no TRUE-SAME pair may be auto-declared DIFFERENT",
        },
        "false_merge": {
            "pass": merge_pass,
            "observed_name_only_merges": metrics["name_only_false_merges"],
            "observed_same_without_strong_id": metrics["structural_same_without_strong_id"],
            "observed_all_false_merges": metrics["auto_same_false_merges"],
            "criterion": "no DIFFERENT pair may be auto-SAME; every SAME must carry a shared strong identifier",
        },
    }


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def render_report(metrics: dict[str, Any], manifest: dict[str, Any]) -> str:
    gate = metrics["gates"]
    matrix = metrics["confusion"]
    bound = metrics["clear_false_negative_attestation"]
    return f"""# Validation Report

Generated by `run_validation.py`; numeric results in this document are emitted from the harness.

## Result

| Gate | Status | Observed |
|---|---:|---:|
| False-negative | {'PASS' if gate['false_negative']['pass'] else 'FAIL'} | {gate['false_negative']['observed']} TRUE-SAME → DIFFERENT |
| False-merge | {'PASS' if gate['false_merge']['pass'] else 'FAIL'} | {gate['false_merge']['observed_name_only_merges']} name-only merges; {gate['false_merge']['observed_same_without_strong_id']} structural leaks |

## Aggregate confusion matrix

| Ground truth | SAME | DIFFERENT | REVIEW |
|---|---:|---:|---:|
| SAME | {matrix['SAME']['SAME']} | {matrix['SAME']['DIFFERENT']} | {matrix['SAME']['REVIEW']} |
| DIFFERENT | {matrix['DIFFERENT']['SAME']} | {matrix['DIFFERENT']['DIFFERENT']} | {matrix['DIFFERENT']['REVIEW']} |

Auto-SAME recall: {metrics['auto_same_recall']:.6f}. Review rate: {metrics['review_rate']:.6f}.

## Exact uncertainty statement

{bound}

## Reproducibility

- Seed schedule: {manifest['trial_seeds']}
- Per-trial sizes: {manifest['sizes_per_trial']}
Interpreter, platform, wall clock, and completion timestamp are recorded in `run-manifest.json` — they are provenance, not results, and are kept out of this report so it re-derives byte-identically on any machine.

See `metrics.json`, `threshold-sweep.csv`, `confusion-matrix.csv`, and `run-manifest.json` for machine-readable evidence.
"""


def emit_evidence(evidence_dir: Path, aggregate_rows: list[dict[str, Any]], primary_rows: list[dict[str, Any]],
                  metrics: dict[str, Any], manifest: dict[str, Any]) -> None:
    evidence_dir.mkdir(parents=True, exist_ok=True)
    (evidence_dir / "metrics.json").write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    matrix_rows = []
    for label in ("SAME", "DIFFERENT"):
        for disposition in ("SAME", "DIFFERENT", "REVIEW"):
            matrix_rows.append({"ground_truth": label, "disposition": disposition,
                                "count": metrics["confusion"][label][disposition]})
    write_csv(evidence_dir / "confusion-matrix.csv", ["ground_truth", "disposition", "count"], matrix_rows)

    sweep_rows = []
    for threshold in (0.75, 0.90, 1.00, 1.15, 1.30):
        scored = score_rows(primary_rows, resolve_pair, ResolutionConfig(decisive_moderate_contradiction=threshold))
        values = summarize(scored)
        sweep_rows.append({
            "decisive_moderate_threshold": f"{threshold:.2f}",
            "clear_false_negatives": values["clear_false_negatives"],
            "false_merges": values["auto_same_false_merges"],
            "auto_same_recall": f"{values['auto_same_recall']:.6f}",
            "review_rate": f"{values['review_rate']:.6f}",
        })
    write_csv(evidence_dir / "threshold-sweep.csv",
              ["decisive_moderate_threshold", "clear_false_negatives", "false_merges", "auto_same_recall", "review_rate"],
              sweep_rows)
    (evidence_dir / "run-manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (evidence_dir / "VALIDATION-REPORT.md").write_text(render_report(metrics, manifest), encoding="utf-8")


def main() -> int:
    args = parse_args()
    if args.trials < 1:
        print("error: --trials must be >= 1", file=sys.stderr)
        return 2
    started_utc = utc_now()
    started = time.perf_counter()
    unit_ok, tests_run = run_unit_tests()
    if not unit_ok:
        print("UNIT TESTS: FAIL", file=sys.stderr)
        return 2
    scorer = select_scorer(args.engine)
    seeds = trial_seeds(args.seed, args.trials)
    all_scored: list[dict[str, Any]] = []
    trial_metrics = []
    primary_rows: list[dict[str, Any]] = []
    print(f"engine={args.engine} unit_tests={tests_run} seed={args.seed} trials={args.trials}")
    print("seed  pairs  true_same  clear_FN  false_merges  name_only_merges  structural_leaks  gate")
    for trial_seed in seeds:
        rows = generate_pairs(trial_seed, args.same, args.different, args.name_only)
        if not primary_rows:
            primary_rows = rows
        scored = score_rows(rows, scorer)
        values = summarize(scored)
        trial_gate = gates(values)
        passed = all(item["pass"] for item in trial_gate.values())
        trial_metrics.append({"seed": trial_seed, **{key: value for key, value in values.items() if key != "confusion"},
                              "gates_pass": passed})
        all_scored.extend(scored)
        print(f"{trial_seed:4d}  {values['pairs']:5d}  {values['true_same_pairs']:9d}  "
              f"{values['clear_false_negatives']:8d}  {values['auto_same_false_merges']:12d}  "
              f"{values['name_only_false_merges']:16d}  {values['structural_same_without_strong_id']:16d}  "
              f"{'PASS' if passed else 'FAIL'}")

    aggregate = summarize(all_scored)
    aggregate["category_dispositions"] = category_summary(all_scored)
    aggregate["trials"] = trial_metrics
    aggregate["gates"] = gates(aggregate)
    aggregate["clear_false_negative_cp_upper_95"] = clopper_pearson_upper(
        aggregate["clear_false_negatives"], aggregate["true_same_pairs"], 0.95)
    aggregate["clear_false_negative_attestation"] = bound_sentence(
        aggregate["clear_false_negatives"], aggregate["true_same_pairs"], 0.95)
    aggregate_pass = all(item["pass"] for item in aggregate["gates"].values())
    elapsed = time.perf_counter() - started
    manifest = {
        "schema_version": "1.0", "engine": args.engine, "command": "python3 " + " ".join(sys.argv),
        "base_seed": args.seed, "trial_seeds": seeds, "trials": args.trials,
        "sizes_per_trial": {"same": args.same, "different": args.different, "name_only": args.name_only,
                            "total": args.same + args.different + args.name_only},
        "unit_tests_run": tests_run, "started_utc": started_utc, "completed_utc": utc_now(),
        "wall_clock_seconds": round(elapsed, 6), **runtime_provenance(),
        "generator_sha256": sha256_file(ROOT / "generate_synthetic_data.py"),
        "identity_engine_sha256": sha256_file(ROOT / "_local" / "identity.py"),
        "network_used": False,
    }
    write_evidence = args.engine == "production" if args.write_evidence is None else args.write_evidence
    if write_evidence:
        # reference-data/ is owned by _tooling/build_reference_data.py (CI-gated);
        # the harness writes evidence only.
        emit_evidence(args.evidence_dir, all_scored, primary_rows, aggregate, manifest)
    print("false_negative_gate=" + ("PASS" if aggregate["gates"]["false_negative"]["pass"] else "FAIL"))
    print("false_merge_gate=" + ("PASS" if aggregate["gates"]["false_merge"]["pass"] else "FAIL"))
    print(aggregate["clear_false_negative_attestation"])
    if not aggregate_pass:
        leaked = [row for row in all_scored if
                  (row["label"] == "SAME" and row["disposition"] == "DIFFERENT") or
                  (row["label"] == "DIFFERENT" and row["disposition"] == "SAME") or
                  (row["disposition"] == "SAME" and not row["shared_strong_identifier"])]
        print(f"LEAKED CASES ({len(leaked)} total; first 12):", file=sys.stderr)
        for row in leaked[:12]:
            print(json.dumps(row, sort_keys=True), file=sys.stderr)
        print("VALIDATION: FAIL (non-zero exit)", file=sys.stderr)
        return 1
    print("VALIDATION: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
