#!/usr/bin/env python3
"""Generate BUILD-NOTES.md exclusively from emitted and regenerated harness results."""

from __future__ import annotations

import json
from pathlib import Path

from _local.attest import bound_sentence, clopper_pearson_upper
from _local.metrics import summarize
from generate_synthetic_data import generate_cases
from negative_control_scorer import score_candidate
from run_validation import gates, score_cases

ROOT = Path(__file__).resolve().parent


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def trial_table(metrics: dict) -> str:
    lines = ["| Seed | Candidates | TRUE BO | Clear FN | Integrity leaks | Unresolved clears | Gate |",
             "|---:|---:|---:|---:|---:|---:|:---:|"]
    for trial in metrics["trials"]:
        lines.append(f"| {trial['seed']} | {trial['candidates']} | {trial['true_beneficial_owners']} | "
                     f"{trial['clear_false_negatives']} | {trial['resolution_integrity_leaks']} | "
                     f"{trial['unresolved_plant_clears']} | {'PASS' if trial['gates_pass'] else 'FAIL'} |")
    return "\n".join(lines)


def console_transcript(metrics: dict, manifest: dict, engine: str) -> str:
    lines = [f"engine={engine} unit_tests={manifest['unit_tests_run']} seed={manifest['base_seed']} trials={manifest['trials']}",
             "seed  candidates  true_BO  clear_FN  integrity_leaks  unresolved_clears  gate"]
    for trial in metrics["trials"]:
        lines.append(f"{trial['seed']:4d}  {trial['candidates']:10d}  {trial['true_beneficial_owners']:7d}  "
                     f"{trial['clear_false_negatives']:8d}  {trial['resolution_integrity_leaks']:15d}  "
                     f"{trial['unresolved_plant_clears']:17d}  {'PASS' if trial['gates_pass'] else 'FAIL'}")
    lines.extend([
        "false_negative_gate=" + ("PASS" if metrics["gates"]["false_negative"]["pass"] else "FAIL"),
        "resolution_integrity_gate=" + ("PASS" if metrics["gates"]["resolution_integrity"]["pass"] else "FAIL"),
        metrics["clear_false_negative_attestation"],
        "VALIDATION: PASS" if all(gate["pass"] for gate in metrics["gates"].values()) else "VALIDATION: FAIL (non-zero exit)",
    ])
    return "\n".join(lines)


def negative_metrics(manifest: dict) -> dict:
    all_scored = []
    trials = []
    sizes = manifest["sizes_per_trial"]
    for seed in manifest["trial_seeds"]:
        cases = generate_cases(seed, sizes["true_owners"], sizes["below"], sizes["unresolved"])
        scored = score_cases(cases, score_candidate)
        values = summarize(scored)
        trial_gate = gates(values)
        trials.append({"seed": seed, **{key: value for key, value in values.items() if key != "confusion"},
                       "gates_pass": all(item["pass"] for item in trial_gate.values())})
        all_scored.extend(scored)
    aggregate = summarize(all_scored)
    aggregate["trials"] = trials
    aggregate["gates"] = gates(aggregate)
    aggregate["clear_false_negative_cp_upper_95"] = clopper_pearson_upper(
        aggregate["clear_false_negatives"], aggregate["true_beneficial_owners"], 0.95)
    aggregate["clear_false_negative_attestation"] = bound_sentence(
        aggregate["clear_false_negatives"], aggregate["true_beneficial_owners"], 0.95)
    return aggregate


def leaked_examples(manifest: dict) -> list[dict]:
    sizes = manifest["sizes_per_trial"]
    cases = generate_cases(manifest["base_seed"], sizes["true_owners"], sizes["below"], sizes["unresolved"])
    selected = []
    for wanted in ("true_concealed_majority_many_subthreshold_shells", "unresolved_opaque_intermediary_below_looking"):
        case = next(item for item in cases if item["category"] == wanted)
        result = score_candidate(case["graph"], case["candidate_id"])
        selected.append({"case_id": case["case_id"], "category": case["category"], "label": case["label"],
                         "disposition": result["disposition"], "effective_ownership": result["effective_ownership"],
                         "graph_fully_resolved": result["graph_fully_resolved"], "reason": result["reason"]})
    return selected


def main() -> int:
    production = load(ROOT / "evidence" / "metrics.json")
    manifest = load(ROOT / "evidence" / "run-manifest.json")
    negative = negative_metrics(manifest)
    leaks = "\n".join(json.dumps(item, sort_keys=True) for item in leaked_examples(manifest))
    reproduce = (ROOT / "REPRODUCE.json").read_text(encoding="utf-8").strip()
    content = f"""# Build Notes

Generated by `generate_build_notes.py` from harness evidence and regenerated negative-control results; reported counts are not hand-entered.

## Passing validation console transcript

```bash
python3 run_validation.py --seed 42 --true-owners 160 --below 240 --unresolved 80 --trials 6
```

Console (`exit 0`):

```text
{console_transcript(production, manifest, 'production')}
```

## Multi-seed stability

{trial_table(production)}

{production['clear_false_negative_attestation']}

## Proof the gates are real

`negative_control_scorer.py` deliberately checks only direct person-to-target ownership. It ignores path aggregation and resolution eligibility.

```bash
python3 run_validation.py --seed 42 --true-owners 160 --below 240 --unresolved 80 --trials 6 --engine negative-control --no-write-evidence
```

Harness result: `exit 1`; both gates printed `FAIL`.

{trial_table(negative)}

Representative leaked cases printed by the same scoring path:

```jsonl
{leaks}
```

The weakened run emitted {negative['clear_false_negatives']} auto-clear false negatives, {negative['resolution_integrity_leaks']} ineligible auto-clears, and {negative['unresolved_plant_clears']} unresolved-plant auto-clears across all trials. These are test-double results, not production metrics.

## REPRODUCE.json entry

```json
{reproduce}
```

## Evidence digest

- Both production gates passed across {manifest['trials']} seeds and {production['candidates']} labelled candidates.
- Production observed {production['clear_false_negatives']} auto-clear false negatives in {production['true_beneficial_owners']} TRUE beneficial owners; exact one-sided 95% upper bound: {production['clear_false_negative_cp_upper_95']:.6f}.
- Production emitted {production['resolution_integrity_leaks']} ineligible auto-clears, {production['unresolved_plant_clears']} unresolved-chain clears, and {production['confirmed_false_positives']} confirmed-owner false positives.

## Vendored primitives

- `_local/metrics.py`: ownership confusion matrix, recall, false-negative, review, and resolution-integrity metrics (engine-local)
- `_local/attest.py`: exact one-sided Clopper-Pearson bound, contextual bound sentence, provenance, UTC, and SHA-256 (engine-local)
- Shared `../_lib/seeding.py`: deterministic RNG, multi-trial seed schedule, and stable sample selection
- Shared `../_lib/ownership.py`: graph validation, path-product propagation, multi-path aggregation, circular convergence/cap diagnostics, target-graph resolution, control-prong detection, and invariant-protected disposition logic — promoted to the shared library for reuse by ownership-adjacent engines
"""
    (ROOT / "BUILD-NOTES.md").write_text(content, encoding="utf-8")
    print("wrote BUILD-NOTES.md from emitted production evidence and regenerated negative-control results")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
